
replicaCount: 1
image:
  repository: app045/maintenance-service
  tag: 6fdbf89
  pullPolicy: IfNotPresent
service:
  port: 8080
resources:
  limits:
    cpu: "1000m"
    memory: "512Mi"
  requests:
    cpu: "500m"
    memory: "256Mi"
nodeSelector: {}
tolerations: []
affinity: {}
